// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwkhtaalkfmqhyfbqudu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3a2h0YWFsa2ZtcWh5ZmJxdWR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyOTYxMTgsImV4cCI6MjA2Mzg3MjExOH0.xpyCEMqUlmHSn-BJkyj9bOpYPWPy-uSH5y98M3cIlfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);